package den.vor.easy.object.factory.constraints.impl;

import den.vor.easy.object.factory.constraints.Bound;
import den.vor.easy.object.factory.constraints.SequenceConstraint;
import den.vor.easy.object.factory.constraints.SequenceConstraintsValues;

/**
 * Greater-than-or-equals constraint (>=).
 * Is applied to the lower bound. Newly set bound is <b>inclusive</b>
 * @param <T> type of object, generated by the factory
 */
public class GeConstraint<T extends Comparable<? super T>> extends SequenceConstraint<T> {

    public GeConstraint(String constraint) {
        super(constraint);
    }

    @Override
    public SequenceConstraintsValues<T> apply(SequenceConstraintsValues<T> constraintsValues, T value) {
        if (value.compareTo(constraintsValues.getMin().getValue()) > 0) {
            constraintsValues.setMin(new Bound<>(value, true));
        }
        return constraintsValues;
    }
}

